### ISSUE TITLE
Error deploying on Ubuntu 18.04 with NGINX installed 

### ISSUE THREAD

**Issue by mukberty** [Lattyware/massivedecks#188]
I ran `sudo npm run build` in the `server` directory.

`node js`  `v8.10.0`
`npm`  `3.5.2`
`npx`  `10.2.2`
 
I get the following error 

```
$ sudo npm run build

> @massivedecks/server@2.0.0 build /home/username/massivedecks/server
> npx tsc

npx: installed 1 in 5.082s
error TS6047: Argument for '--target' option must be 'ES3', 'ES5', or 'ES6'.
error TS6046: Argument for '--module' option must be 'commonjs', 'amd', 'system' or 'umd'.
error TS5023: Unknown compiler option 'incremental'.
error TS5023: Unknown compiler option 'resolveJsonModule'.
error TS5023: Unknown compiler option 'strict'.
error TS5023: Unknown compiler option 'strictNullChecks'.
error TS5023: Unknown compiler option 'strictFunctionTypes'.
error TS5023: Unknown compiler option 'strictBindCallApply'.
error TS5023: Unknown compiler option 'strictPropertyInitialization'.
error TS5023: Unknown compiler option 'noImplicitThis'.
error TS5023: Unknown compiler option 'alwaysStrict'.
error TS5023: Unknown compiler option 'noImplicitReturns'.
error TS5023: Unknown compiler option 'noFallthroughCasesInSwitch'.
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'allowSyntheticDefaultImports'.

npm ERR! Linux 5.4.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @massivedecks/server@2.0.0 build: `npx tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @massivedecks/server@2.0.0 build script 'npx tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @massivedecks/server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @massivedecks/server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @massivedecks/server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/massivedecks/server/npm-debug.log
```
In the `client` directory:

```
sudo npm run build

> @massivedecks/client@2.0.0 prebuild /home/username/massivedecks/client
> sed -i "s/\"dev\"/\"${MD_VERSION:-${SOURCE_VERSION:-unknown}-dev}\"/g" src/elm/MassiveDecks/Version.elm


> @massivedecks/client@2.0.0 build /home/username/massivedecks/client
> npx webpack --mode=production

npx: installed 121 in 14.44s
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN webpack-cli@3.3.12 requires a peer of webpack@4.x.x but none was installed.
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at runCommand.then (/home/username/.npm/_npx/22963/lib/node_modules/webpack/bin/webpack.js:119:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }

npm ERR! Linux 5.4.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @massivedecks/client@2.0.0 build: `npx webpack --mode=production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @massivedecks/client@2.0.0 build script 'npx webpack --mode=production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @massivedecks/client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx webpack --mode=production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @massivedecks/client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @massivedecks/client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/massivedecks/client/npm-debug.log

```

How can I fix this ?
Thank You :)

**Comment by Lattyware** [comment]
It won't be the issue here, but you shouldn't need to use `sudo` for this, and I would in fact highly recommend against it.

I believe the issue here is you need to run `npm install` first to get the dependencies, it should work after that.

**Comment by mukberty** [comment]
Hmm. It still won't work. Is there anything else I can try ?

**Comment by Lattyware** [comment]
You'd need to show me the new error output for me to be able to say anything more.

**Comment by nemesv** [comment]
You should upgrade your node version to 13.x or higher according to the https://github.com/Lattyware/massivedecks/wiki/Setting-Up-A-Development-Environment. 
I had a similar error with node 10.4 and upgrading the latest node.js fixed for me.

**Comment by Lattyware** [comment]
Yeah, we keep current with Node, I'll change that to say 14.x as that is what we are currently actively using and testing, and we don't officially aim to support any older versions.

**Comment by mukberty** [comment]
Thank you @nemesv . I upgraded to `v14.13.1` and it works now .
