### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ShadowVoyd** [Lattyware/massivedecks#77]
Received the following error when attempting to run the project using SBT
forgive me if I may have missed something as this is all new to myself.

[error] (compile:compileIncremental) java.lang.NullPointerException
[debug] > load-failed

**Comment by Lattyware** [comment]
Hrm, this is probably a problem with a newer version of SBT, at a guess.

Can you give me *all* the output, and the exact command you used? It's hard to say what's going on with so little to go on.

**Comment by ShadowVoyd** [comment]
`
C:\massivedecks>sbt run
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support
was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support
was removed in 8.0
[info] Loading project definition from C:\massivedecks\project
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at sbt.IO$.pathSplit(IO.scala:797)
        at sbt.IO$.parseClasspath(IO.scala:912)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:6
6)
        at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzing
Compiler.scala:188)
        at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAn
alyzingCompiler.scala:166)
        at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.sca
la:176)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:152)
        at sbt.Compiler$.compile(Compiler.scala:138)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala
:860)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
51)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
49)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown
 Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?`

**Comment by ShadowVoyd** [comment]
C:\massivedecks>sbt run
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support
was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support
was removed in 8.0
[info] Loading project definition from C:\massivedecks\project
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at sbt.IO$.pathSplit(IO.scala:797)
        at sbt.IO$.parseClasspath(IO.scala:912)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:6
6)
        at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzing
Compiler.scala:188)
        at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAn
alyzingCompiler.scala:166)
        at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.sca
la:176)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:152)
        at sbt.Compiler$.compile(Compiler.scala:138)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala
:860)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
51)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:8
49)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
8)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown
 Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by Lattyware** [comment]
Hrm, this looks to be an SBT issue - as suggested [here](https://stackoverflow.com/questions/39451862/sbt-command-throws-null-pointer-excepion), it may be that you are using a version of Java too new for the version of SBT? Have you tried JDK 8?

I'd like to update this project to work with modern versions of everything, and the plan is to do that once the next version of Elm comes out to have it all in sync, but I don't have the time at the moment.

If you do have the time and willingness, then the best course of action would probably be to update the project to the latest version of the play framework (and, by extension, the latest version of SBT) - I'd happily accept a pull request.
